display:
  default:
    display_options:
      fields:
        name:
          label: Name
  page_1:
    display_options:
      fields:
        name:
          label: Name
  rest_export_1:
    display_options:
      fields:
        name:
          label: Name
