display:
  default:
    display_options:
      fields:
        name:
          label: Name
      arguments:
        field_media_of_target_id:
          exception:
            title: Vše
  page_1:
    display_options:
      menu:
        title: Média
      fields:
        media_bulk_form:
          action_title: Akce
        name:
          label: Name
  rest_export_1:
    display_options:
      fields:
        name:
          label: Name
